defaults: &defaults
  site:
    name: 宇宙ニュース
    page_title: ニュース記事一覧
    page_description: 宇宙に関するニュース記事を一覧にしています。
    page_keywords: 宇宙,ニュース,News,記事,まとめ
    meta:
      ogp:
        type: article
        image_path: http://localhost:3000/images/NASA7.jpg
  intro:
    posts:
      - id: 100
        image: "NASA7.jpg"
      - id: 101
        image: "NASA5-1.jpg"
      - id: 102
        image: "NASA10.jpg"
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
