defaults: &defaults
  site:
    name: 宇宙ニュース
    page_title: ニュース記事一覧
    page_description: 宇宙に関するニュース記事を一覧にしています。
    page_keywords: 宇宙,最新,ニュース,News,記事,まとめ
    meta:
      ogp:
        type: article
        image_path: http://localhost:3000/images/og.jpg
  intro:
    posts:
      - id: 136
        image: "NASA7.jpg"
      - id: 101
        image: "NASA5-1.jpg"
      - id: 130
        image: "NASA10.jpg"
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  site:
    name: 宇宙ニュース
    page_title: ニュース記事一覧
    page_description: 宇宙に関するニュース記事を一覧にしています。
    page_keywords: 宇宙,最新,ニュース,News,記事,まとめ
    meta:
      ogp:
        type: article
        image_path: https://xn--zck9awe6du60xdda.com/images/og.jpg
  intro:
    posts:
      - id: 116
        image: "NASA7.jpg"
      - id: 101
        image: "NASA5-1.jpg"
      - id: 110
        image: "NASA10.jpg"
